// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	pool "github.com/valyala/bytebufferpool"
)

func tpl_code(buffer *pool.ByteBuffer) {

	for i := 0; i < 3; i++ {
		buffer.WriteString(`<li>item</li>`)

	}

	var list = []string{"Uno", "Dos", "Tres",
		"Cuatro", "Cinco", "Seis"}
	for _, item := range list {
		buffer.WriteString(`<li>`)
		WriteEscString(item, buffer)
		buffer.WriteString(`</li>`)
	}
	buffer.WriteString(`<p>`)
	WriteEscString("This code is &lt;escaped&gt;!", buffer)
	buffer.WriteString(`</p><p>`)
	WriteEscString("This code is <escaped>!", buffer)
	buffer.WriteString(`</p><p>`)
	buffer.WriteString("This code is <strong>not</strong> escaped!")
	buffer.WriteString(`</p><p>`)
	buffer.WriteString("This code is <strong>not</strong> escaped!")
	buffer.WriteString(`</p>`)

}
