// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	pool "github.com/valyala/bytebufferpool"
)

func tpl_doctype(buffer *pool.ByteBuffer) {

	buffer.WriteString(`<!DOCTYPE html><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML Basic 1.1//EN"><!DOCTYPE html>`)

}
