// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	"github.com/valyala/bytebufferpool"
)

func tpl_doctype(buffer *bytebufferpool.ByteBuffer) {

	buffer.WriteString(`<!DOCTYPE html><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML Basic 1.1//EN"><!DOCTYPE html>`)

}
