// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	"github.com/valyala/bytebufferpool"
)

func Output(user string, buffer *bytebufferpool.ByteBuffer) {

	buffer.WriteString(`<p></p><p>    In the midst of a large amount of plain
    text, suddenly a wild <appeared>
</appeared></p><script></script><p><div><div id="function"></div></div></p>`)

}
