// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	pool "github.com/valyala/bytebufferpool"
)

func tpl_tags(buffer *pool.ByteBuffer) {

	buffer.WriteString(`<ul><li>Item A</li><li>Item B</li><li>Item C</li></ul><img/><a><img/></a><foo/><foo bar="baz"/>`)

}
