// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	pool "github.com/valyala/bytebufferpool"
)

func tpl_indexa(buffer *pool.ByteBuffer) {

	buffer.WriteString(`<!DOCTYPE html><html><head><style>/* style.css */
h1 {
  color: red;
}
</style></head><body><h1>My Site</h1><p>Welcome to my super lame site.</p><script>// script.js
console.log('You are awesome');
</script></body></html>`)

}
