// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	pool "github.com/valyala/bytebufferpool"
)

func tpl_index(buffer *pool.ByteBuffer) {

	buffer.WriteString(`<!DOCTYPE html><html><head><title>My Site</title><script src="/javascripts/jquery.js"></script><script src="/javascripts/app.js"></script></head><body><h1>My Site</h1><p>Welcome to my super lame site.</p><footer id="footer"><p>Copyright (c) foobar</p></footer></body></html>`)

}
