// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	"github.com/valyala/bytebufferpool"
)

func tpl_layoutb(buffer *bytebufferpool.ByteBuffer) {

	buffer.WriteString(`<html><head><script src="/vendor/jquery.js"></script><script src="/vendor/caustic.js"></script></head><body></body></html>`)

}
