// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	pool "github.com/valyala/bytebufferpool"
)

func tpl_pagea(title string, petName string, buffer *pool.ByteBuffer) {

	buffer.WriteString(`<html><head><title>My Site - `)
	WriteEscString(title, buffer)
	buffer.WriteString(`</title><script src="/jquery.js"></script><script src="/pets.js"></script></head><body><h1>`)
	WriteEscString(title, buffer)
	buffer.WriteString(`</h1>`)
	var pets = []string{"cat", "dog"}
	for _, petName := range pets {
		buffer.WriteString(`<p>`)
		WriteEscString(petName, buffer)
		buffer.WriteString(`</p>`)
	}
	buffer.WriteString(`<div id="footer"><p>some footer content</p></div></body></html>`)

}
