// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	pool "github.com/valyala/bytebufferpool"
)

func Jade_pet(petName string, buffer *pool.ByteBuffer) {

	buffer.WriteString(`<p>`)
	WriteEscString(petName, buffer)
	buffer.WriteString(`</p>`)

}
