// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	"github.com/valyala/bytebufferpool"
)

func tpl_pet(petName string, buffer *bytebufferpool.ByteBuffer) {

	buffer.WriteString(`<p>`)
	WriteEscString(petName, buffer)
	buffer.WriteString(`</p>`)

}
