// Code generated by "jade.go"; DO NOT EDIT.

package jade

import (
	"github.com/Joker/jade/testdata/imp/model"
	pool "github.com/valyala/bytebufferpool"
)

func Simple(u *model.User, st []model.Story, buffer *pool.ByteBuffer) {

	buffer.WriteString(`<html><body><h1>`)
	WriteEscString(u.FirstName, buffer)
	buffer.WriteString(`</h1><p>Here's a list of your favorite colors:</p><ul>`)

	for _, colorName := range u.FavoriteColors {
		buffer.WriteString(`<li>`)
		WriteEscString(colorName, buffer)
		buffer.WriteString(`</li>`)
	}
	buffer.WriteString(`</ul><ul>`)

	for _, story := range st {
		buffer.WriteString(`<li>`)
		WriteInt(int64(story.StoryId), buffer)
		buffer.WriteString(`</li><li>`)
		WriteInt(int64(story.UserId), buffer)
		buffer.WriteString(`</li><li>`)
		WriteEscString(story.UserName, buffer)
		buffer.WriteString(`</li>`)
	}
	buffer.WriteString(`</ul></body></html>`)

}
